version: '3.8'

services:
  # Сервер
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: glossary-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=4444
    volumes:
      - ./server/data:/app/data
    networks:
      - app-network

  # Клиент
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: glossary-client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge